/**
 * GitHub Radar - Generate Digest
 */

const fs = require("fs");
const path = require("path");
const { formatNum } = require("./fetch-trending");

function getToday() {
  return new Date().toISOString().split("T")[0];
}

function generateMarkdown(data) {
  const today = getToday();
  const totalRepos = Object.values(data).reduce((sum, cat) => sum + cat.repos.length, 0);
  const hotRepos = Object.values(data).reduce(
    (sum, cat) => sum + cat.repos.filter(r => r.stars_per_day >= 5).length, 0
  );

  let md = "";
  md += `# 🔭 GitHub Radar — Daily Digest\n\n`;
  md += `**Date:** ${today}  \n`;
  md += `**Repos tracked:** ${totalRepos} | **Hot (5+ ⭐/day):** ${hotRepos}  \n`;
  md += `**Categories:** AI/LLM/Agents, Crypto/Web3, General Trending  \n\n`;
  md += `---\n\n`;

  md += `## Contents\n\n`;
  for (const [id, cat] of Object.entries(data)) {
    if (cat.repos.length > 0) {
      md += `- [${cat.name}](#${id}) (${cat.repos.length} repos)\n`;
    }
  }
  md += `\n---\n\n`;

  for (const [id, cat] of Object.entries(data)) {
    if (cat.repos.length === 0) continue;

    md += `## ${cat.name}\n\n`;

    const top3 = cat.repos.slice(0, 3);
    if (top3.length > 0) {
      md += `### 🏆 Top 3\n\n`;
      top3.forEach((r, i) => {
        const medal = ["🥇", "🥈", "🥉"][i];
        const hotTag = r.stars_per_day >= 5 ? " 🔥" : "";
        md += `${medal} **[${r.full_name}](${r.html_url})**${hotTag}  \n`;
        md += `${r.description}  \n`;
        md += `⭐ ${formatNum(r.stars)} (+${r.stars_per_day}/day) | 🍴 ${formatNum(r.forks)} | ${r.language}  \n\n`;
      });
    }

    md += `### All repos\n\n`;
    md += `| # | Repo | Stars | ⭐/day | Language | Description |\n`;
    md += `|---|------|-------|--------|----------|-------------|\n`;

    cat.repos.forEach((r, i) => {
      const hot = r.stars_per_day >= 5 ? " 🔥" : "";
      const desc = r.description.length > 80 ? r.description.slice(0, 80) + "..." : r.description;
      md += `| ${i + 1} | [${r.full_name}](${r.html_url})${hot} | ${formatNum(r.stars)} | +${r.stars_per_day} | ${r.language} | ${desc} |\n`;
    });

    md += `\n---\n\n`;
  }

  md += `## 📊 Summary\n\n`;

  const allRepos = Object.values(data).flatMap(cat => cat.repos);
  const hottest = allRepos.filter(r => r.stars_per_day >= 5).sort((a, b) => b.stars_per_day - a.stars_per_day).slice(0, 5);

  if (hottest.length > 0) {
    md += `### 🔥 Hottest repos today (5+ ⭐/day)\n\n`;
    hottest.forEach(r => {
      md += `- **[${r.full_name}](${r.html_url})** — ${r.stars_per_day}⭐/day (${formatNum(r.stars)} total) — ${r.language}\n`;
    });
    md += `\n`;
  }

  const langCount = {};
  allRepos.forEach(r => {
    langCount[r.language] = (langCount[r.language] || 0) + 1;
  });
  const topLangs = Object.entries(langCount).sort((a, b) => b[1] - a[1]).slice(0, 5);
  md += `### Top languages today\n\n`;
  topLangs.forEach(([lang, count]) => {
    md += `- ${lang}: ${count} repos\n`;
  });

  md += `\n---\n\n`;
  md += `*Generated by [GitHub Radar](https://github.com/xnotok-ops/github-radar) — Built by [@xnotok](https://x.com/xnotok)*\n`;

  return md;
}

function saveDigest(markdown) {
  const today = getToday();
  const digestDir = path.join(__dirname, "..", "digests");

  if (!fs.existsSync(digestDir)) {
    fs.mkdirSync(digestDir, { recursive: true });
  }

  const filePath = path.join(digestDir, `${today}.md`);
  fs.writeFileSync(filePath, markdown, "utf-8");
  console.log(`Digest saved: ${filePath}`);
  return filePath;
}

function generateTelegramMessage(data) {
  const today = getToday();
  const allRepos = Object.values(data).flatMap(cat => cat.repos);
  const hottest = allRepos.filter(r => r.stars_per_day >= 5).sort((a, b) => b.stars_per_day - a.stars_per_day).slice(0, 5);

  let msg = `🔭 <b>GitHub Radar — ${today}</b>\n\n`;

  if (hottest.length > 0) {
    msg += `🔥 <b>Hottest repos:</b>\n\n`;
    hottest.forEach((r, i) => {
      msg += `${i + 1}. <a href="${r.html_url}">${r.full_name}</a>\n`;
      msg += `   ⭐ ${formatNum(r.stars)} (+${r.stars_per_day}/day) | ${r.language}\n`;
      msg += `   ${r.description.slice(0, 80)}\n\n`;
    });
  }

  for (const [id, cat] of Object.entries(data)) {
    if (cat.repos.length === 0) continue;
    const top = cat.repos[0];
    msg += `📌 <b>${cat.name}</b>: <a href="${top.html_url}">${top.full_name}</a> (${formatNum(top.stars)}⭐)\n`;
  }

  msg += `\n📄 Full digest: https://xnotok-ops.github.io/github-radar`;
  msg += `\n\n<i>by @xnotok</i>`;

  return msg;
}

module.exports = { generateMarkdown, saveDigest, generateTelegramMessage };
